---
- name: Reboot server
  hosts: linux-reboot
  become: yes
  become_user: root
  roles:
    - reboot

  vars_prompt:
    - name: "reboot"
      prompt: "Are you sure you want to reboot server (yes/no)?"
      private: no
      default: "no"
