---
# file: roles/syslog_client/tasks/main.yml
- name: ensure rsyslog is installed
  apt: name=rsyslog state=latest update_cache=yes
  tags: syslog

- name: write the remote syslog config file
  template: src=99-remote.conf.j2 dest=/etc/rsyslog.d/99-remote.conf
  notify:
  - restart rsyslog
  tags: syslog
  when: syslog_mode == "remote"

- name: remove the remote syslog config file
  file: path=/etc/rsyslog.d/99-remote.conf state=absent
  tags: syslog
  when: syslog_mode != "remote"
