---
# file: roles/syslog_client/tasks/main.yml
- name: ensure rsyslog is installed
  apt: name=rsyslog state=latest
  tags: syslog

- name: write the remote syslog config file
  template: src=99-remote.conf.j2 dest=/etc/rsyslog.d/99-remote.conf
  notify:
  - restart rsyslog
  tags: syslog
